import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report

# 1. Load the results
# These files are generated by baseline_eval.py and rag_eval.py
baseline_df = pd.read_csv('baseline_results.csv')
rag_df = pd.read_csv('rag_results.csv')

# Clean RAG results: Filter out API errors to ensure scientific integrity
rag_df = rag_df[rag_df['RAG_Predicted'] != "Error"]

# Merge datasets on 'Question' to ensure an apples-to-apples comparison
combined = pd.merge(baseline_df, rag_df, on="Question", suffixes=('_base', '_rag'))

# 2. Calculate and Print Comparative Results
base_acc = combined['Baseline_Correct'].mean() * 100
rag_acc = combined['RAG_Correct'].mean() * 100

print(f"\n" + "="*45)
print(f"       PERFORMANCE COMPARISON REPORT")
print(f"="*45)
print(f"Zero-Shot Accuracy (Baseline):  {base_acc:.2f}%")
print(f"RAG-Enhanced Accuracy (Proposed): {rag_acc:.2f}%")
print(f"Net Accuracy Improvement:        {rag_acc - base_acc:.2f}%")
print(f"="*45 + "\n")

# 3. Print Detailed Precision/Recall/F1 Table
# This is the 'Data Science' core of your thesis
labels = sorted(combined['Actual_rag'].unique())
print("--- Detailed Classification Metrics (RAG) ---")
print(classification_report(combined['Actual_rag'], combined['RAG_Predicted'], target_names=labels))

# 4. Generate Confusion Matrix
cm = confusion_matrix(combined['Actual_rag'], combined['RAG_Predicted'], labels=labels)

plt.figure(figsize=(10, 7))
sns.heatmap(cm, annot=True, fmt='d', xticklabels=labels, yticklabels=labels, cmap='Blues')
plt.xlabel('Predicted Category')
plt.ylabel('Actual Category')
plt.title('Confusion Matrix: RAG-Enhanced Classification')
plt.tight_layout()
plt.savefig('confusion_matrix.png')
print("✅ Saved 'confusion_matrix.png'")

# 5. Generate Accuracy Comparison Bar Chart
plt.figure(figsize=(8, 6))
methods = ['Zero-Shot (Baseline)', 'RAG-Enhanced (Proposed)']
accuracies = [base_acc, rag_acc]
colors = ['#ff9999', '#66b3ff']

plt.bar(methods, accuracies, color=colors)
plt.ylabel('Accuracy (%)')
plt.title('Comparison: Zero-Shot vs. RAG-Enhanced')
plt.ylim(0, 100)

# Annotate bars with accuracy percentage
for i, v in enumerate(accuracies):
    plt.text(i, v + 2, f"{v:.1f}%", ha='center', fontweight='bold')

plt.tight_layout()
plt.savefig('accuracy_comparison.png')
print("✅ Saved 'accuracy_comparison.png'")

plt.show()